# Generated by Django 3.1.3 on 2020-11-14 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('playlist_title', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Narration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=10)),
                ('narration_title', models.CharField(max_length=250)),
                ('narration_editor', models.CharField(max_length=250)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audioApp.playlist')),
            ],
        ),
    ]
