# Generated by Django 3.1.3 on 2020-11-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioApp', '0002_auto_20201114_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='narration',
            name='narration_editor',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='playlist',
            name='company_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
