# Generated by Django 3.1.3 on 2020-11-15 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioApp', '0003_auto_20201114_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narration',
            name='narration_editor',
        ),
    ]
