# Generated by Django 3.1.3 on 2020-11-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioApp', '0004_remove_narration_narration_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='narration',
            name='narration_editor',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
