# Generated by Django 3.1.3 on 2020-11-15 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioApp', '0005_narration_narration_editor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='narration',
            old_name='narration_editor',
            new_name='total_narration_time',
        ),
    ]
